### PR TITLE
admin controls

### PR DESCRIPTION
**Pull request by aeither**
solve #24

### CODE REVIEW

**Comment by orpheuslummis** [comment]
Screenshot 2024-01-14 at 12 58 21
This one doesn't seem to work: when writing a number, both fields are updated and then can't submit.
Also, each input field should have a label.

**Comment by orpheuslummis** [comment]
Screenshot 2024-01-14 at 16 03 24

now i can input the numbers but the button doesn't become clickable.

**Comment by aeither** [comment]
> Screenshot 2024-01-14 at 16 03 24
> now i can input the numbers but the button doesn't become clickable.

Probably because of this
`require(increase > decrease, "Increase threshold must be greater than decrease threshold");`

**Comment by aeither** [comment]
pulled "fix: Sign of setAuctionTimeThresholds requirement (#47)".

**Review by orpheuslummis — APPROVED** [review]
LGTM

**Pull request merged**
